// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDniIa2tGoSGHGa4JGfdjHhJfjYnVCyHU',
    appId: '1:137966539827:web:1c818ad4a6dc5ddaf37f46',
    messagingSenderId: '137966539827',
    projectId: 'chat-app-36c72',
    authDomain: 'chat-app-36c72.firebaseapp.com',
    storageBucket: 'chat-app-36c72.firebasestorage.app',
    measurementId: 'G-C85T2G842C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa6NnPtBLUL63MP153kFqeHSc6LVmo9KI',
    appId: '1:137966539827:android:1ecaec7238d083aaf37f46',
    messagingSenderId: '137966539827',
    projectId: 'chat-app-36c72',
    storageBucket: 'chat-app-36c72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0SqMQIY8KiTZN81x5YIDsTRDLoEwvndc',
    appId: '1:137966539827:ios:ad278c4b7bfedba1f37f46',
    messagingSenderId: '137966539827',
    projectId: 'chat-app-36c72',
    storageBucket: 'chat-app-36c72.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0SqMQIY8KiTZN81x5YIDsTRDLoEwvndc',
    appId: '1:137966539827:ios:ad278c4b7bfedba1f37f46',
    messagingSenderId: '137966539827',
    projectId: 'chat-app-36c72',
    storageBucket: 'chat-app-36c72.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDniIa2tGoSGHGa4JGfdjHhJfjYnVCyHU',
    appId: '1:137966539827:web:5a06a45e0de874bdf37f46',
    messagingSenderId: '137966539827',
    projectId: 'chat-app-36c72',
    authDomain: 'chat-app-36c72.firebaseapp.com',
    storageBucket: 'chat-app-36c72.firebasestorage.app',
    measurementId: 'G-K9W1TRTV6F',
  );

}